"""Add bank_name and bank_email columns

Revision ID: 10cf304fd028
Revises: 
Create Date: 2024-07-03 11:25:04.732354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10cf304fd028'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_id', table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('value', sa.FLOAT(), nullable=False),
    sa.Column('currency', sa.VARCHAR(), nullable=False),
    sa.Column('business', sa.VARCHAR(), nullable=False),
    sa.Column('business_type', sa.VARCHAR(), nullable=True),
    sa.Column('bank_name', sa.VARCHAR(), nullable=False),
    sa.Column('bank_email', sa.VARCHAR(), nullable=False),
    sa.Column('expense_priority', sa.VARCHAR(length=4), nullable=True),
    sa.Column('expense_type', sa.VARCHAR(length=13), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_id', 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###
