from datetime import datetime
from email.message import Message
from typing import Protocol

from ..models.enums import ExpensePriority, ExpenseType


class HasMessageConstructor(Protocol):
    def __init__(self, msg: Message) -> None:
        ...


class TransactionMail(Protocol):
    def get_body(self) -> str: ...
    def get_business(self) -> str: ...
    def get_business_type(self) -> str | None: ...
    def get_value_and_currency(self) -> tuple[str, float]: ...
    def get_date(self) -> datetime: ...
    def get_expense_type(self) -> ExpenseType | None: ...
    def get_expense_priority(self) -> ExpensePriority | None: ...
